const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('ctrl', {
  minimize:            ()          => ipcRenderer.send('window-minimize'),
  close:               ()          => ipcRenderer.send('window-close'),
  acceptEula:          ()          => ipcRenderer.invoke('accept-eula'),
  // Updater
  updaterCheck:        ()          => ipcRenderer.invoke('updater-check'),
  updaterDownload:     ()          => ipcRenderer.invoke('updater-download'),
  updaterInstall:      ()          => ipcRenderer.invoke('updater-install'),
  updaterGetLog:       ()          => ipcRenderer.invoke('updater-get-log'),
  updaterGetVersion:   ()          => ipcRenderer.invoke('updater-get-version'),
  onUpdaterEvent:      (cb)        => ipcRenderer.on('updater-event', (_, data) => cb(data)),
  loadLoading:         ()          => ipcRenderer.invoke('load-loading'),
  loadDashboard:       ()          => ipcRenderer.invoke('load-dashboard'),
  logout:              ()          => ipcRenderer.invoke('logout'),
  getConfig:           ()          => ipcRenderer.invoke('get-config'),
  saveConfig:          (c)         => ipcRenderer.invoke('save-config', c),
  detectApps:          ()          => ipcRenderer.invoke('detect-apps'),
  getRunningAudio:     ()          => ipcRenderer.invoke('get-running-audio'),
  launchApp:           (p)         => ipcRenderer.invoke('launch-app', p),
  getSysinfo:          ()          => ipcRenderer.invoke('get-sysinfo'),
  getDiskTemp:         ()          => ipcRenderer.invoke('get-disk-temp'),
  getUptime:           ()          => ipcRenderer.invoke('get-uptime'),
  setSystemMute:       (m)         => ipcRenderer.invoke('set-system-mute', m),
  setAppVolume:        (proc, vol) => ipcRenderer.invoke('set-app-volume', proc, vol),
  muteApp:             (proc, mute) => ipcRenderer.invoke('mute-app', proc, mute),
  setAutostart:        (e)         => ipcRenderer.invoke('set-autostart', e),
  startShutdownTimer:  (s)         => ipcRenderer.invoke('start-shutdown-timer', s),
  cancelShutdownTimer: ()          => ipcRenderer.invoke('cancel-shutdown-timer'),
  pickExe:             ()          => ipcRenderer.invoke('pick-exe'),
  pickImage:           ()          => ipcRenderer.invoke('pick-image'),
  checkGpuDriver:      ()          => ipcRenderer.invoke('check-gpu-driver'),
  freeRam:             ()          => ipcRenderer.invoke('free-ram'),
  cleanupTemp:         ()          => ipcRenderer.invoke('cleanup-temp'),
  getAutostart:        ()          => ipcRenderer.invoke('get-autostart'),
  toggleAutostartEntry:(n,e,h)     => ipcRenderer.invoke('toggle-autostart-entry', n, e, h),
  getCleanupPreview:   ()          => ipcRenderer.invoke('get-cleanup-preview'),
  getTemps:            ()          => ipcRenderer.invoke('get-temps'),
  getSystemSnapshot:   ()          => ipcRenderer.invoke('get-system-snapshot'),
  openAdmin:           ()          => ipcRenderer.invoke('open-admin'),
  mullvadStatus:       ()          => ipcRenderer.invoke('mullvad-status'),
  mullvadConnect:      ()          => ipcRenderer.invoke('mullvad-connect'),
  mullvadDisconnect:   ()          => ipcRenderer.invoke('mullvad-disconnect'),
  getDefenderStatus:   ()          => ipcRenderer.invoke('get-defender-status'),
  setDefender:         (e)         => ipcRenderer.invoke('set-defender', e),
  spotifyControl:      (a)         => ipcRenderer.invoke('spotify-control', a),
  getSpotifyTrack:     ()          => ipcRenderer.invoke('get-spotify-track'),
});
